name: first workflow  # Fixed spelling from 'frist' to 'first'

on: push

jobs:
  first_job:  # Fixed spelling from 'frist_job' to 'first_job'
    runs-on: ubuntu-latest

    steps:
      - name: Welcome to my workflow
        run: echo "Welcome"
