name: Cowsay Pipeline

on: push

jobs:
  cowsay_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cowsay and Dependencies
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Download Dog Cowfile
        run: wget -O /usr/share/cowsay/cows/dog.cow https://raw.githubusercontent.com/paulkaefer/cowsay-files/master/cows/dog.cow

      - name: Make Script Executable
        run: chmod +x dog.sh

      - name: Run Dog Cowfile
        run: cowsay -f dog "Hello from GitHub Actions!"
