name: first workflow  # Fixed spelling from 'frist' to 'first'

on: push

jobs:
  first_job:  # Fixed spelling from 'frist_job' to 'first_job'
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4

      - name: run the script
        run: |
         chmod +x cowart.sh
         ./dog.sh